import { Nunito_Sans } from 'next/font/google'

import './globals.css'
import classes from './layout.module.scss'

import Menu from "./menu/menu"
import Link from 'next/link'
import NotificationCenter from '@/components/firebase/notification'

const nunito = Nunito_Sans({
  weight:['300','400','600'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Início',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) { 
  return (
    <html lang="pt-br" className={ nunito.className }>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="manifest" href={ `/manifest.json?v=${ new Date().getTime() }` } />
      </head>
      <body>
        <div className={ classes.Layout }>
          <aside className={ classes.Bar }>🐲</aside>
          <Menu />
          <main className={ classes.Main }>
            <div>
              {/* <NotificationCenter /> */}
            </div>
            <div className={ classes.Content }>
              {children}
            </div>
            <footer className={ classes.Footer }>Created by @<Link href="https://twitter.com/wllnrds">wllnrds</Link></footer>
          </main>
        </div>
      </body>
    </html>
  )
}
